import React from "react";
import { Pattern } from "react-hexgrid";

const imageSize = { x: 3.4, y: 2.75 };

const Patterns = () => {
	return (
		<>
			<Pattern
				id="land0000"
				link="./images/positionImages/land0000.png"
				size={imageSize}
			/>
			<Pattern
				id="land0001"
				link="./images/positionImages/land0001.png"
				size={imageSize}
			/>
			<Pattern
				id="land0010"
				link="./images/positionImages/land0010.png"
				size={imageSize}
			/>
			<Pattern
				id="land0011"
				link="./images/positionImages/land0011.png"
				size={imageSize}
			/>
			<Pattern
				id="land0100"
				link="./images/positionImages/land0100.png"
				size={imageSize}
			/>
			<Pattern
				id="land0101"
				link="./images/positionImages/land0101.png"
				size={imageSize}
			/>
			<Pattern
				id="land0110"
				link="./images/positionImages/land0110.png"
				size={imageSize}
			/>
			<Pattern
				id="land0111"
				link="./images/positionImages/land0111.png"
				size={imageSize}
			/>
			<Pattern
				id="land1000"
				link="./images/positionImages/land1000.png"
				size={imageSize}
			/>
			<Pattern
				id="land1001"
				link="./images/positionImages/land1001.png"
				size={imageSize}
			/>
			<Pattern
				id="land1010"
				link="./images/positionImages/land1010.png"
				size={imageSize}
			/>
			<Pattern
				id="land1011"
				link="./images/positionImages/land1011.png"
				size={imageSize}
			/>
			<Pattern
				id="land1100"
				link="./images/positionImages/land1100.png"
				size={imageSize}
			/>
			<Pattern
				id="land1101"
				link="./images/positionImages/land1101.png"
				size={imageSize}
			/>
			<Pattern
				id="land1110"
				link="./images/positionImages/land1110.png"
				size={imageSize}
			/>
			<Pattern
				id="land1111"
				link="./images/positionImages/land1111.png"
				size={imageSize}
			/>
			<Pattern
				id="water0000"
				link="./images/positionImages/water0000.png"
				size={imageSize}
			/>
			<Pattern
				id="water0001"
				link="./images/positionImages/water0001.png"
				size={imageSize}
			/>
			<Pattern
				id="water0010"
				link="./images/positionImages/water0010.png"
				size={imageSize}
			/>
			<Pattern
				id="water0011"
				link="./images/positionImages/water0011.png"
				size={imageSize}
			/>
			<Pattern
				id="water0100"
				link="./images/positionImages/water0100.png"
				size={imageSize}
			/>
			<Pattern
				id="water0101"
				link="./images/positionImages/water0101.png"
				size={imageSize}
			/>
			<Pattern
				id="water0110"
				link="./images/positionImages/water0110.png"
				size={imageSize}
			/>
			<Pattern
				id="water0111"
				link="./images/positionImages/water0111.png"
				size={imageSize}
			/>
			<Pattern
				id="water1000"
				link="./images/positionImages/water1000.png"
				size={imageSize}
			/>
			<Pattern
				id="water1001"
				link="./images/positionImages/water1001.png"
				size={imageSize}
			/>
			<Pattern
				id="water1010"
				link="./images/positionImages/water1010.png"
				size={imageSize}
			/>
			<Pattern
				id="water1011"
				link="./images/positionImages/water1011.png"
				size={imageSize}
			/>
			<Pattern
				id="water1100"
				link="./images/positionImages/water1100.png"
				size={imageSize}
			/>
			<Pattern
				id="water1101"
				link="./images/positionImages/water1101.png"
				size={imageSize}
			/>
			<Pattern
				id="water1110"
				link="./images/positionImages/water1110.png"
				size={imageSize}
			/>
			<Pattern
				id="water1111"
				link="./images/positionImages/water1111.png"
				size={imageSize}
			/>
			<Pattern
				id="flag0000"
				link="./images/positionImages/flag0000.png"
				size={imageSize}
			/>
			<Pattern
				id="flag0001"
				link="./images/positionImages/flag0001.png"
				size={imageSize}
			/>
			<Pattern
				id="flag0010"
				link="./images/positionImages/flag0010.png"
				size={imageSize}
			/>
			<Pattern
				id="flag0011"
				link="./images/positionImages/flag0011.png"
				size={imageSize}
			/>
			<Pattern
				id="flag0100"
				link="./images/positionImages/flag0100.png"
				size={imageSize}
			/>
			<Pattern
				id="flag0101"
				link="./images/positionImages/flag0101.png"
				size={imageSize}
			/>
			<Pattern
				id="flag0110"
				link="./images/positionImages/flag0110.png"
				size={imageSize}
			/>
			<Pattern
				id="flag0111"
				link="./images/positionImages/flag0111.png"
				size={imageSize}
			/>
			<Pattern
				id="flag1000"
				link="./images/positionImages/flag1000.png"
				size={imageSize}
			/>
			<Pattern
				id="flag1001"
				link="./images/positionImages/flag1001.png"
				size={imageSize}
			/>
			<Pattern
				id="flag1010"
				link="./images/positionImages/flag1010.png"
				size={imageSize}
			/>
			<Pattern
				id="flag1011"
				link="./images/positionImages/flag1011.png"
				size={imageSize}
			/>
			<Pattern
				id="flag1100"
				link="./images/positionImages/flag1100.png"
				size={imageSize}
			/>
			<Pattern
				id="flag1101"
				link="./images/positionImages/flag1101.png"
				size={imageSize}
			/>
			<Pattern
				id="flag1110"
				link="./images/positionImages/flag1110.png"
				size={imageSize}
			/>
			<Pattern
				id="flag1111"
				link="./images/positionImages/flag1111.png"
				size={imageSize}
			/>
			<Pattern
				id="red0000"
				link="./images/positionImages/red0000.png"
				size={imageSize}
			/>
			<Pattern
				id="red0001"
				link="./images/positionImages/red0001.png"
				size={imageSize}
			/>
			<Pattern
				id="red0010"
				link="./images/positionImages/red0010.png"
				size={imageSize}
			/>
			<Pattern
				id="red0011"
				link="./images/positionImages/red0011.png"
				size={imageSize}
			/>
			<Pattern
				id="red0100"
				link="./images/positionImages/red0100.png"
				size={imageSize}
			/>
			<Pattern
				id="red0101"
				link="./images/positionImages/red0101.png"
				size={imageSize}
			/>
			<Pattern
				id="red0110"
				link="./images/positionImages/red0110.png"
				size={imageSize}
			/>
			<Pattern
				id="red0111"
				link="./images/positionImages/red0111.png"
				size={imageSize}
			/>
			<Pattern
				id="red1000"
				link="./images/positionImages/red1000.png"
				size={imageSize}
			/>
			<Pattern
				id="red1001"
				link="./images/positionImages/red1001.png"
				size={imageSize}
			/>
			<Pattern
				id="red1010"
				link="./images/positionImages/red1010.png"
				size={imageSize}
			/>
			<Pattern
				id="red1011"
				link="./images/positionImages/red1011.png"
				size={imageSize}
			/>
			<Pattern
				id="red1100"
				link="./images/positionImages/red1100.png"
				size={imageSize}
			/>
			<Pattern
				id="red1101"
				link="./images/positionImages/red1101.png"
				size={imageSize}
			/>
			<Pattern
				id="red1110"
				link="./images/positionImages/red1110.png"
				size={imageSize}
			/>
			<Pattern
				id="red1111"
				link="./images/positionImages/red1111.png"
				size={imageSize}
			/>
			<Pattern
				id="blue0000"
				link="./images/positionImages/blue0000.png"
				size={imageSize}
			/>
			<Pattern
				id="blue0001"
				link="./images/positionImages/blue0001.png"
				size={imageSize}
			/>
			<Pattern
				id="blue0010"
				link="./images/positionImages/blue0010.png"
				size={imageSize}
			/>
			<Pattern
				id="blue0011"
				link="./images/positionImages/blue0011.png"
				size={imageSize}
			/>
			<Pattern
				id="blue0100"
				link="./images/positionImages/blue0100.png"
				size={imageSize}
			/>
			<Pattern
				id="blue0101"
				link="./images/positionImages/blue0101.png"
				size={imageSize}
			/>
			<Pattern
				id="blue0110"
				link="./images/positionImages/blue0110.png"
				size={imageSize}
			/>
			<Pattern
				id="blue0111"
				link="./images/positionImages/blue0111.png"
				size={imageSize}
			/>
			<Pattern
				id="blue1000"
				link="./images/positionImages/blue1000.png"
				size={imageSize}
			/>
			<Pattern
				id="blue1001"
				link="./images/positionImages/blue1001.png"
				size={imageSize}
			/>
			<Pattern
				id="blue1010"
				link="./images/positionImages/blue1010.png"
				size={imageSize}
			/>
			<Pattern
				id="blue1011"
				link="./images/positionImages/blue1011.png"
				size={imageSize}
			/>
			<Pattern
				id="blue1100"
				link="./images/positionImages/blue1100.png"
				size={imageSize}
			/>
			<Pattern
				id="blue1101"
				link="./images/positionImages/blue1101.png"
				size={imageSize}
			/>
			<Pattern
				id="blue1110"
				link="./images/positionImages/blue1110.png"
				size={imageSize}
			/>
			<Pattern
				id="blue1111"
				link="./images/positionImages/blue1111.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield0000"
				link="./images/positionImages/airfield0000.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield0001"
				link="./images/positionImages/airfield0001.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield0010"
				link="./images/positionImages/airfield0010.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield0011"
				link="./images/positionImages/airfield0011.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield0100"
				link="./images/positionImages/airfield0100.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield0101"
				link="./images/positionImages/airfield0101.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield0110"
				link="./images/positionImages/airfield0110.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield0111"
				link="./images/positionImages/airfield0111.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield1000"
				link="./images/positionImages/airfield1000.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield1001"
				link="./images/positionImages/airfield1001.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield1010"
				link="./images/positionImages/airfield1010.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield1011"
				link="./images/positionImages/airfield1011.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield1100"
				link="./images/positionImages/airfield1100.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield1101"
				link="./images/positionImages/airfield1101.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield1110"
				link="./images/positionImages/airfield1110.png"
				size={imageSize}
			/>
			<Pattern
				id="airfield1111"
				link="./images/positionImages/airfield1111.png"
				size={imageSize}
			/>
			<Pattern
				id="missile0000"
				link="./images/positionImages/missile0000.png"
				size={imageSize}
			/>
			<Pattern
				id="missile0001"
				link="./images/positionImages/missile0001.png"
				size={imageSize}
			/>
			<Pattern
				id="missile0010"
				link="./images/positionImages/missile0010.png"
				size={imageSize}
			/>
			<Pattern
				id="missile0011"
				link="./images/positionImages/missile0011.png"
				size={imageSize}
			/>
			<Pattern
				id="missile0100"
				link="./images/positionImages/missile0100.png"
				size={imageSize}
			/>
			<Pattern
				id="missile0101"
				link="./images/positionImages/missile0101.png"
				size={imageSize}
			/>
			<Pattern
				id="missile0110"
				link="./images/positionImages/missile0110.png"
				size={imageSize}
			/>
			<Pattern
				id="missile0111"
				link="./images/positionImages/missile0111.png"
				size={imageSize}
			/>
			<Pattern
				id="missile1000"
				link="./images/positionImages/missile1000.png"
				size={imageSize}
			/>
			<Pattern
				id="missile1001"
				link="./images/positionImages/missile1001.png"
				size={imageSize}
			/>
			<Pattern
				id="missile1010"
				link="./images/positionImages/missile1010.png"
				size={imageSize}
			/>
			<Pattern
				id="missile1011"
				link="./images/positionImages/missile1011.png"
				size={imageSize}
			/>
			<Pattern
				id="missile1100"
				link="./images/positionImages/missile1100.png"
				size={imageSize}
			/>
			<Pattern
				id="missile1101"
				link="./images/positionImages/missile1101.png"
				size={imageSize}
			/>
			<Pattern
				id="missile1110"
				link="./images/positionImages/missile1110.png"
				size={imageSize}
			/>
			<Pattern
				id="missile1111"
				link="./images/positionImages/missile1111.png"
				size={imageSize}
			/>
		</>
	);
};

export default Patterns;
