//redux actions

export const INITIAL_GAMESTATE = "INITIAL_GAMESTATE";
export const SET_USERFEEDBACK = "SET_USERFEEDBACK";
export const START_PLAN = "START_PLAN";
export const CANCEL_PLAN = "CANCEL_PLAN";
export const CONFIRM_PLAN = "CONFIRM_PLAN";
export const PLANNING_SELECT = "PLANNING_SELECT";
export const PLAN_WAS_CONFIRMED = "PLAN_WAS_CONFIRMED";
export const DELETE_PLAN = "DELETE_PLAN";
export const UNDO_MOVE = "UNDO_MOVE";
export const CONTAINER_MOVE = "CONTAINER_MOVE";
export const NEWS_PHASE = "NEWS_PHASE";
export const PURCHASE_PHASE = "PURCHASE_PHASE";
export const SHOP_PURCHASE = "SHOP_PURCHASE";
export const SHOP_REFUND = "SHOP_REFUND";
export const SHOP_CLEAR = "SHOP_CLEAR";
export const SHOP_TRANSFER = "SHOP_TRANSFER";
export const COMBAT_PHASE = "COMBAT_PHASE";
export const NEW_ROUND = "NEW_ROUND";
export const SLICE_CHANGE = "SLICE_CHANGE";
export const PIECES_MOVE = "PIECES_MOVE";
export const PLACE_PHASE = "PLACE_PHASE";
export const MENU_SELECT = "MENU_SELECT";
export const BATTLEPOPUP_MINIMIZE_TOGGLE = "BATTLEPOPUP_MINIMIZE_TOGGLE";
export const POSITION_SELECT = "POSITION_SELECT";
export const PIECE_CLICK = "PIECE_CLICK";
export const PIECE_CLEAR_SELECTION = "PIECE_CLEAR_SELECTION";
export const MAIN_BUTTON_CLICK = "MAIN_BUTTON_CLICK";
export const PIECE_PLACE = "PIECE_PLACE";
export const BATTLE_PIECE_SELECT = "BATTLE_PIECE_SELECT";
export const TARGET_PIECE_SELECT = "TARGET_PIECE_SELECT";
export const ENEMY_PIECE_SELECT = "ENEMY_PIECE_SELECT";
export const EVENT_BATTLE = "EVENT_BATTLE";
export const EVENT_REFUEL = "EVENT_REFUEL";
export const UNDO_FUEL_SELECTION = "UNDO_FUEL_SELECTION";
export const BATTLE_FIGHT_RESULTS = "BATTLE_FIGHT_RESULTS";
export const REFUEL_RESULTS = "REFUEL_RESULTS";
export const REFUELPOPUP_MINIMIZE_TOGGLE = "REFUELPOPUP_MINIMIZE_TOGGLE";
export const NO_MORE_EVENTS = "NO_MORE_EVENTS";
export const CLEAR_BATTLE = "CLEAR_BATTLE";
export const TANKER_CLICK = "TANKER_CLICK";
export const AIRCRAFT_CLICK = "AIRCRAFT_CLICK";
export const NEWSPOPUP_MINIMIZE_TOGGLE = "NEWSPOPUP_MINIMIZE_TOGGLE";

export const RODS_FROM_GOD_SELECTING = "RODS_FROM_GOD_SELECTING";
export const RODS_FROM_GOD_SELECTED = "RODS_FROM_GOD_SELECTED";

export const INSURGENCY_SELECTING = "INSURGENCY_SELECTING";
export const INSURGENCY_SELECTED = "INSURGENCY_SELECTED";

export const REMOTE_SENSING_SELECTING = "REMOTE_SENSING_SELECTING";
export const REMOTE_SENSING_SELECTED = "REMOTE_SENSING_SELECTED";

export const HIGHLIGHT_POSITIONS = "HIGHLIGHT_POSITIONS";
